# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "MTLkZrnCLnYd1+mgZjse9tD/yJT6GEyMUr25HCwrhkfwLotsB/sNY2Gs+9JMc80Are3TLD272FcAAy8yMKBtev+7q5acPfgGPU01eC1+ucPzYNRUYjc7oa4mIlCAy+NdOXBY6KNCh3FooC6OZd7NALIFiO4EqgQmufhred+LOP8j4MA6QmX8SCrq8vfTy+l4acUYKdxrdigo4HyHAK2i9HcsR/x+C+WP3nFsfqAtbE5VZhTnupfEB4Obj333TA6X8hmSj6HablynqkHFnNuu++VDMgklOQ756b3u58b+OQtCmbfD2EJY6Ee9ex+wRZ/Mavsp1hE6sK9l8hiGeaT0S/HcjSSJGbzdwfkAKKNTC734q+f4q1QHWHeJokr77Gg0KyuOErkm5sDaxyZvEQHx+dBwHYkL9Ut7F06lMvOLYFtXZM/jRwCBE6FyjUVyVPQRDHgH/rLNsOXr9R9DywJ+31MN7KhMvrqnHEk1RfApfhHE2Lvid+FdJ+AAfoNRm/x/figlBP+56PGYu0doHiJuC/FkDXwEkKgqr5uR2HXA13RZAm56WI6m1ok/F19CpCMSfDdSj/FS1TZ+Lydm9RV0LFDJrIOEO4VjcxCm9qqq4UoydjXp5EDJFoBlzBQUydkHzptVrn+IlJOCPmfYS66euZnHeWsmUDkm62fBZfA8Hsk="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
