travis:
  secure:
    BINSTAR_TOKEN: R5hzUWhCr93S3zK7P8y95WJJpAif54lgUQyhawk9GoKAlIS3REXNmwnVWhLlc2hzxcjUge7WLECAb8yu9lUotOeT/5rw078VpOPOOfi4u4HLtw0h5vadCw+8m0sHh0Kmra+4ZvhMN52fmyGVsRUhI4x2dkGnGQMKt4a8toOrYtmnFF/LDcg/rxYZ+hScVwrmRPGg2gjGDDayrKWUTMPydZ5dGHeGJnj1fPmN7NS2D8FAKPeXC9ByMBNIOtQPWJJO1LJHPf0fe3+OBqJXp35ZasANblGdmol9cNyR4ecCnwoZZET79fFEDLrPm2Cs5GLyohOCySpgIlxLJffoSTOVjICT7z+0Lo/cYEg9VIHYVG3B+LCLqH/nQQ1Z5KtFaFsqdTl+NFIUSxqgUzzJ50KwyqvPJ8E9Z/XkaWTDn+mqfJGzxQDPz7m8vsXuvK1Qqwv88GlFZvAt+5YVDBuetSsRRTXkJQu4Ip4VYJjFNEhfR3cl7yJF4icSEHM0DD7gbXDseIV1rWN+j212//KPeJRN7O9OLJ1T1o8dpaxYcsAX2XogwM1WLofxGeF6wOZc36soOHCdJrcNdGDnlPoJ0INm9O6hS06IdD8Rt33zJIc8ZZ7T4PdNSNV2fMiNAFHppPfmnWXHf1Ivm4x1XEwX3J8gjTZknN8HUKXyLWJuwACJO6I=
appveyor:
  secure:
    BINSTAR_TOKEN: /XxwAsgp0EItmAhoPSov/h0BtAFNj2BuuEqnhgaP9l7Rw2yLBM1lD+3q4LvpVm3B
